### ISSUE TITLE
Authentication doesn't support API Key authentication

### ISSUE THREAD

**Issue by jhackamack** [bodsch/ruby-grafana#12]
The Grafana::Login module does not support API Key authentication: https://grafana.com/docs/grafana/latest/http_api/auth/#create-api-token.  Grafana supports an API auth based model using the Authentication header with the provided API key, but the module expects a username and password.    Grafana can support a custom username of `api_key` with the password being the generated API key but given that the Login module posts to `/login` the API Key is not checked there so the request fails.

**Comment by bodsch** [comment]
Thanks for the hint!

Which Grafana version is meant?
The implemented api_key function worked in version 4 and in early 5 versions.

**Comment by bodsch** [comment]
I've opened an new [branch](development/support-grafana-6) to fix this issue.
in my very small bubble it already works, but i still have to integrate some tests to ensure compatibility with Grafana 5.

**Comment by bodsch** [comment]
see https://github.com/bodsch/ruby-grafana/releases/tag/v1.1.0
